### ISSUE TITLE
the code running on the arduino is golang alos using tinygo ?

### ISSUE THREAD

**Issue by gedw99** [fiwippi/currents#1]
Hey @fiwippi 

This looks really accessible for a golang coder like me. and a good way to teach my kid some electronics and coding.

Is some of the golang code running on the arduino UNO ? https://tinygo.org/docs/reference/microcontrollers/arduino/

Just trying to get my head around the topology.

**Comment by gedw99** [comment]
also in the makefile. 

i think with gio and windows you dont need to compile the way your doing it.

https://github.com/gioui/gio/tree/main/cmd/gogio does all that and more.

For example:

``` 

go install gioui.org/cmd/gogio@latest

gio -o ./bin/binary.exe -target windows .

```

**Comment by fiwippi** [comment]
Hey,

1. The only code written on the Arduino is written using C with the [FastLED](https://github.com/FastLED/FastLED) library, all the golang code is client side for the GUI and interpreting the computer's audio stream
2. I'll take a look at it, seems interesting

Further explanation of the go code in the `pkg` directory:
- The `audio` folder contains all code used to parse audio streams and generate a colour based off of them
- The `gui` folder contains all the `gio` code for running the gui
- The `session` folder contains the code the computer uses to interface with the arduino over serial bus

If you have any more questions feel free to ask

**Comment by gedw99** [comment]
Thanks
